### ISSUE TITLE
Cannot visit mint website

### ISSUE THREAD

**Issue by monsterbitar** [cashninjas/ninjas.cash#1]
After clicking to go to the mint from the main ninjas.cash website, I end up with a blank page and the following in my console output:

> assets/mint-2346be2c.js:20 Uncaught SyntaxError: Unexpected reserved word

I am using the Falkon browser, which is based on QtWebEngine.

The page opens fine in Firefox.

**Comment by zquestz** [comment]
I dug into this and unfortunately it is not fixable right now.

The issue is that we use top level `await` statements that are not supported in QtWebEngine. When I went through our code and fixed the issue, it popped up in our libauth dependency.

Unfortunately, until QtWebEngine can support this, people should stick to Firefox or a Chromium based browser.

**Comment by monsterbitar** [comment]
ah, that's what it was.

I should've known, we hit the same thing in some internal tooling for the bchbull - our solution was a TLA polyfill.

That said, the number of ninja-minting users who'll be on an uncommon browser is likely not going to be important, so I'll close this issue.
